services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "33000:8080"
    environment:
      - OPENAI_API_KEY=sk-xxxxxxxxx
      - WEBUI_SECRET_KEY=xxxx
      - OPENAI_API_BASE_URL=https://openai.com/api/v1
    volumes:
      - ./data:/app/backend/data

